[system]
output-filename = "flood_field"
output-type = "DICOM"
pixel-data = "UINT-16"
additional-fields = true
blur-radius = 0
spectrum-table = "C:/PAWLIN/spectrum.csv"
invert = false
logarithmize = true
scaling-coefficient = 512.0
use-rescale-slope = false

[system.target-resolution]
width = 1024
height = 1024

[detector]
type = "CURVED"
distance = 1040.0
radius = 1040.0

[detector.resolution]
width = 1024
height = 1024

[detector.size]
width = 1024
height = 1024

[[filter]]
type = "DIST"
distance = 20.0
radius = 10.0
material = "Al"

[[collimator]]
orientation = "VERTICAL"
type = "SYMMETRICAL"
distance = 10.0
shift = 8.0

[[collimator]]
orientation = "HORIZONTAL"
type = "SYMMETRICAL"
distance = 100.0
shift = 8.0
