[system]
output-filename = "flood_field"
output-type = "DICOM"
pixel-data = "UINT-16"
additional-fields = false
blur-radius = 0
spectrum-table = "/home/armemius/PAWLIN/data/spectrum.csv"
invert = false
logarithmize = true
scaling-coefficient = 100.0
use-rescale-slope = false

[system.target-resolution]
width = 512
height = 512

[detector]
type = "FLAT"
distance = 1040.0
radius = 1040.0
rotation = 45.0

[detector.resolution]
width = 512
height = 512

[detector.size]
width = 512
height = 512

#[[filter]]
#id = "Cu Slab"
#type = "SLAB"
#distance = 20.0
#thickness = 2.0
#material = "Cu"

#[[filter]]
#type = "BOWTIE-CYLINDRICAL"
#distance = 400.0
#thickness = 400.0
#radius = 800.0
#material = "PMMA"
#rotation = 45.0

[[filter]]
type = "DIST"
distance = 800.0
radius = 100.0
material = "PMMA"
#rotation = -45.0

#[[collimator]]
#orientation = "VERTICAL"
#type = "RIGHT"
#distance = 1040.0
#shift = 100.0


